- name: install mysql-server
  ansible.builtin.dnf:
    name: 'mysql-server'
    state: present

- name: restart nd enable the service
  ansible.builtin.systemd_service:
    state: restarted
    name: mysqld
    enabled: true

- name: mysql_secure_installation --set-root-pass RoboShop@1
  ansible.builtin.shell: mysql_secure_installation --set-root-pass RoboShop@1
